### ISSUE TITLE
Profile images wave 1

### ISSUE THREAD

**Issue by samsohani** [mrvlu/lancebotics#7]

**Comment by asonance** [comment]
requirements:
-delete images pre-existing in the folder

suggestions:

-seperate the images so that they are ordered in folders by team. 
         -this makes everything more organized. 
         -some code would have to be changed to reflect this but nothing significant. 
         -also eliminates issues of members of different teams having the same name.
         -makes things easier in the future for future updates to the website ex. updating for next year's team, basically a service to future website team

-change names of pictures to have first name and initial of last name
         -also for organization purposes
         -have to make changes in the code, nothing too significant
         -makes things easier in the future
       
i will do this in my own fork as well
